# Generated by Django 5.2.8 on 2026-01-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
    ]
