# Generated by Django 6.0.1 on 2026-02-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_is_fake'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='verdict',
            field=models.CharField(default='Genuine', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
