# Generated by Django 5.2.8 on 2026-01-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_method_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='fulfillment_type',
            field=models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical')], default='physical', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fulfillment_type',
            field=models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical')], default='physical', max_length=20),
        ),
    ]
